eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
  service:
    url: ${EUREKA_SERVER_ADDRESS:http://localhost/8761/eureka}
# okta:
#   oauth2:
#     issuer: https://integrator-1885339.okta.com/oauth2/default
#     audience: api://default
